-test md5
-- some code
-- im a master now
-- ver 1 is now closed
-- add code for ver 2
-- ver 2 is now closed
-- add code for ver 2.5
-- ver 2.5 is now closed
-- add code for ver 3
-- ver 3 is now closed